### ISSUE TITLE
Control test

### ISSUE THREAD

**Issue by focalstrategy** [seedifferently/the-great-web-framework-shootout#8]
It would be nice to see the results without any framework - particularly for the first one.

Something like:

<? echo "Lorem ipsum...." ?>

for PHP.

I don't currently use a framework, and often wonder what overhead it actually adds.

**Comment by seedifferently** [comment]
Richard,

Thanks for the suggestion. I had that in an earlier form of the tests but decided to remove it because I felt like it took away from the main purpose of the results (comparing _frameworks_). Perhaps I will include them in a future update...or if you're curious you can just boot up the AMI and see for yourself.
